---
- name: OpenJDK RPM をコピーします。
  copy: 
    src: "{{ item }}"
    dest: /tmp
    mode: 0664
  with_items: "{{ openjdk_items }}"
  tags:
    - jenkins
    - deploy
    - openjdk_inst

- name: OpenJDKをインストールします。
  yum: 
    name: "/tmp/{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ openjdk_items }}"
  tags:
    - jenkins
    - deploy
    - openjdk_inst

- name: Jenkins RPM をコピーします。
  copy: 
    src: "{{ jekins_package_url }}"
    dest: /tmp
    mode: 0664
  tags:
    - jenkins
    - deploy
    - jenkins_inst
 
- name: Jenkins Repositoryを取得します。
  get_url: 
    url: "{{ jenkins_repo }}"
    dest: "{{ yum_repojitory_path }}/jenkins.repo"
  tags:
    - jenkins
    - deploy
    - jenkins_inst

- name: Jenkins Keyを設定します。
  rpm_key: state=present key={{ jenkins_key }}
  tags:
    - jenkins
    - deploy
    - jenkins_inst

- name: Jenkinsをインストールします。
  yum: 
    name: "/tmp/{{ jekins_package_url }}"
    state: present
  ignore_errors: yes
  tags:
    - jenkins
    - deploy
    - jenkins_inst
    
- name: Jenkinsをスタートします。
  service: 
    name: jenkins
    state: started
    enabled: yes
  tags:
    - jenkins
    - deploy
    - jenkins_inst

- name: Jenkins port{{ jenkins_port }} 有効化まで待機します。
  wait_for: port={{ jenkins_port }} timeout=60
  tags:
    - jenkins
    - deploy
    - jenkins_inst

- name: Jenkinsサービス有効まで待機します。
  shell: curl -o /dev/null -w %{http_code} {{ my_jenkins_params.url }}/ 2> /dev/null
  register: result
  until: result.stdout.find('403') != -1
  retries: 20
  delay: 3
  changed_when: false
  tags:
    - jenkins
    - deploy
    - jenkins_inst

  