---

- name: Jenkins Setting Delete
  file: path={{ jenkins_parent_dir }}/jenkins state=absent
  tags:
    - jenkins
    - deploy
    - init_setting
    
- name: 初期設定済みファイルを配備
  unarchive: src={{ jenkins_initset_file }} dest={{ jenkins_parent_dir }}
  tags:
    - jenkins
    - deploy
    - init_setting

- name: 初期設定済みプロキシファイルを配備
  template: 
    src: proxy.xml.j2
    dest: /var/lib/jenkins/proxy.xml
    owner: jenkins
    group: jenkins
    mode: 0644
    backup: yes
  tags:
    - jenkins
    - deploy
    - init_setting
- name: ReStart jenkins
  service: name=jenkins state=restarted enabled=yes
  tags:
    - jenkins
    - deploy
    - init_setting

- name: Wait for port {{ jenkins_port }} availability
  wait_for: port={{ jenkins_port }} timeout=60
  tags:
    - jenkins
    - deploy
    - init_setting

