--- 
- name: Get jenkins cli
  get_url: url={{ jenkins_cli_url }} dest={{ jenkins_cli_dest }}
  register: result
  until: result.msg.find("Request failed") == -1
  retries: 5
  delay: 10
  tags:
    - jenkins
    - plugin

- name: Create updates directory
  file: path={{ jenkins_updates_dir }} state=directory mode=0755
  tags:
    - jenkins
    - plugin

- name: Create jenkins plugin file
  shell: >
    curl -L {{ jenkins_updates_center_url }} | sed '1d;$d' > {{ jenkins_updates_json_path }}
    creates={{ jenkins_updates_json_path }}
  tags:
    - jenkins
    - plugin

- name: JenkinsPlugin "Timestamper"
  jenkins_plugin:
    name: Timestamper
    with_dependencies: yes
    params: "{{ my_jenkins_params }}"
  ignore_errors: True
  tags:
    - jenkins
    - plugin

- name: JenkinsPlugin "thinBackup"
  jenkins_plugin:
    name: thinBackup
    with_dependencies: yes
    params: "{{ my_jenkins_params }}"
  ignore_errors: True
  tags:
    - jenkins
    - plugin

- name: JenkinsPlugin "Job Configuration History Plugin"
  jenkins_plugin:
    name: jobConfigHistory
    with_dependencies: yes
    params: "{{ my_jenkins_params }}"
  ignore_errors: True
  tags:
    - jenkins
    - plugin

- name: JenkinsPlugin "Role Strategy Plugin"
  jenkins_plugin:
    name: role-strategy
    with_dependencies: yes
    params: "{{ my_jenkins_params }}"
  ignore_errors: True
  tags:
    - jenkins
    - plugin

- name: JenkinsPlugin "Subversion Plugin"
  jenkins_plugin:
    name: subversion
    with_dependencies: yes
    params: "{{ my_jenkins_params }}"
  ignore_errors: True
  tags:
    - jenkins
    - plugin

- name: JenkinsPlugin "SSH Slaves plugin"
  jenkins_plugin:
    name: ssh-slaves
    with_dependencies: yes
    params: "{{ my_jenkins_params }}"
  ignore_errors: True
  tags:
    - jenkins
    - plugin

- name: JenkinsPlugin "Parameterized Trigger Plugin"
  jenkins_plugin:
    name: parameterized-trigger
    with_dependencies: yes
    params: "{{ my_jenkins_params }}"
  ignore_errors: True
  tags:
    - jenkins
    - plugin
    
    
    
- name: ReStart jenkins
  service: name=jenkins state=reloaded enabled=yes
  tags:
    - jenkins
    - deploy
    - plugin
    
- name: ReStart jenkins
  service: name=jenkins state=restarted enabled=yes
  tags:
    - jenkins
    - deploy
    - plugin

- name: Wait for port {{ jenkins_port }} availability
  wait_for: port={{ jenkins_port }} timeout=60
  tags:
    - jenkins
    - deploy
    - plugin
