---
- name: ansible作業ディレクトリを初期化
  file: 
    path: "{{ ansible_home.dir }}"
    state: absent
  tags: 
    - 05_WorkdirMake
    
- name: ansible作業ディレクトリにエクスポート
  subversion: 
    username: "{{ svn_info.user }}"
    password: "{{ svn_info.pass }}"
    force: yes
    dest: "{{ ansible_home.dir }}"
    repo: "{{ svn_info.url }}"
    export: yes
  tags: 
    - 05_WorkdirMake
    
- name:  ansible作業ディレクトリパーミッション変更
  file: 
    path: "{{ ansible_home.dir }}"
    state: directory
    group: "{{ ansible.user_name }}"
    owner: "{{ ansible.user_name }}"
    mode: 0755
  tags: 
    - 05_WorkdirMake

- name:  ansible作業ファイル所有者変更
  file: 
    path: "{{ ansible_home.dir }}"
    state: directory
    recurse: yes
    group: "{{ ansible.user_name }}"
    owner: "{{ ansible.user_name }}"
  tags: 
    - 05_WorkdirMake

- name:  ansible作業ファイル(sh)パーミッション変更
  file: 
    path: "{{ item }}"
    mode: 0755
  with_fileglob: 
    - "{{ ansible_home.dir }}/*.sh"
  tags: 
    - 05_WorkdirMake

- name: ファイル"{{ ansible_hosts_file }}"に"{{ ansible_inst_hosts }}"を追記
  lineinfile: 
    dest={{ ansible_hosts_file }}
    line={{ item }}
  with_items: 
   - "{{ ansible_inst_hosts }}"
  tags: 
    - 05_WorkdirMake
    