---
- name: グループ"{{ usergroup.ansible_group.name }}"を追加 
  group: 
    name={{usergroup.ansible_group.name}}

- name: ユーザ"{{ usergroup.ansible_user.name }}"を追加 
  user: 
    name={{ usergroup.ansible_user.name }}
    password="{{ usergroup.ansible_user.password | password_hash('sha512') }}"
    groups={{ usergroup.ansible_user.group }}
    state=present
    generate_ssh_key=yes
    ssh_key_type=rsa
    ssh_key_bits=2048
