---
- name: Configure SELinux Disabled setting
  selinux: 
    state: disabled
  tags: 
    - 02_OsSetting

- name: Configure/ Locale Setting
  replace: 
    dest: /etc/sysconfig/i18n
    replace: 'ja_JP.UTF-8'
    regexp: 'de_DE.UTF-8'
    backup: yes
  tags: 
    - 02_OsSetting

- name: Configure/ TimeZone setting
  replace: 
    dest: /etc/sysconfig/clock
    replace: 'Asia/Tokyo'
    regexp: 'Europe/Berlin'
    backup: yes
  tags: 
    - 02_OsSetting

- name: Configure/ TimeZone setting
  file: 
    src: /usr/share/zoneinfo/Asia/Tokyo
    dest: /etc/localtime
    state: link
    force: yes
  tags: 
    - 02_OsSetting

- name: Configure/ Locale Setting Enable Now
  shell: . /etc/sysconfig/i18n
  tags: 
    - 02_OsSetting

- name: ファイル"{{ hosts_file }}"に"{{ inst_hosts }}"を追記
  lineinfile: 
    dest={{ hosts_file }}
    line={{ item }}
  with_items: 
   - "{{ inst_hosts }}"
  tags: 
    - 02_OsSetting
   